---
title: "WEEK2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r Week2_SeqNumbers}
x <- 11:30
 x
seq(0,1, length=11)
seq(rnorm(20))
seq(1,9, by = 2) # difference by 2
seq(-20,-1, by = 2.5) # difference by 2.5
seq(1,9, by = pi)# difference by pi
seq(1,6, by = 3)
seq(3.575, 7.125, by=0.05)
seq(20) # same as 1:20


```

```{r Week2_Vectors}
x <- c("omaha",16,16,8,30,70) 
x
y <- c("wiu",22,18,22,16,78)
y
x[1]
x[c(2: 5)]
x[x >10] 
y[1]
y[c(2, 4)]
y[y >1]

```

```{r Week2_MissingValues}
x <- c(1, 2, NaN, NA, -20)
 is.na(x)  ## Selects for missing values of 'Nan' and 'NA'
x <- c(-1, -2, NA, -10, -3)
  is.na(x)  ## Selects for missing values of 'NA'
is.nan(x)
x <- c(0, 100, NaN, NA, NaN)
 is.na(x)
 is.nan(x)
 which(is.na(x))
 sum(is.na(x))
 
```

```{r Week2_SubsettingVectors}
x <- c("b","a", "b", "c", "c", "d", "a","b")
x[(1:length(x))[x == "b"]]
x[1]
x[2]
x[1:4]
x[c(1, 3, 4)]    ## For any random order
x[x > "a"]      ## Greater than a
y <- x > "a"    ## Greater than a interms of TRUE/FALSE
y
x[u]

```

```{r Week2_MatricesDataFrame}
m <- matrix(1:9, nrow = 3, ncol = 3)
 m
 dim(m)
 attributes(m)
 dim
 
m <- 1:10
m
dim(m) <- c(2, 5)
m
x <- data.frame(foo = 1:6, bar = c(T, T, F, F,T,T))
x

```

